//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsData.SagePaymentsAPI {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
        "", ConfigurationName="SagePaymentsAPI.TRANSACTION_PROCESSINGSoap")]
    public interface TRANSACTION_PROCESSINGSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_CREDIT_OR_REFUND", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_CREDIT_OR_REFUND(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_AUTHONLY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_AUTHONLY(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_CREDIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_CREDIT(string M_ID, string M_KEY, string T_AMT, string T_REFERENCE);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_FORCE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_FORCE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_AUTH, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_VOID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_VOID(string M_ID, string M_KEY, string T_REFERENCE);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_PRIOR_AUTH_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_PRIOR_AUTH_SALE(string M_ID, string M_KEY, string T_AMT, string T_SHIPPING, string T_TAX, string T_AUTH, string T_REFERENCE);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_PPD_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_PPD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_PPD_CREDIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_PPD_CREDIT(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_CCD_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_CCD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_EIN, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_CREDIT_BY_REFERENCE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_CREDIT_BY_REFERENCE(string M_ID, string M_KEY, string T_AMT, string T_REFERENCE);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_CCD_CREDIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_CCD_CREDIT(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_EIN, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_WEB_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_WEB_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_SSN, 
                    string C_DL_STATE_CODE, 
                    string C_DL_NUMBER, 
                    string C_DOB);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_VOID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_VOID(string M_ID, string M_KEY, string T_REFERENCE);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_RCK_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_RCK_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_ARC_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_ARC_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string C_CHECK_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_TEL_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_TEL_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_SWIPED_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_SWIPED_SALE(string M_ID, string M_KEY, string T_AMT, string T_TRACKDATA);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_SWIPED_AUTHONLY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_SWIPED_AUTHONLY(string M_ID, string M_KEY, string T_AMT, string T_TRACKDATA);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_SWIPED_CREDIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_SWIPED_CREDIT(string M_ID, string M_KEY, string T_AMT, string T_TRACKDATA);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_KEYED_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_KEYED_SALE(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_KEYED_SALE_WITH_AVS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_KEYED_SALE_WITH_AVS(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP, string C_ADDRESS, string C_ZIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_KEYED_AUTHONLY_WITH_AVS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_KEYED_AUTHONLY_WITH_AVS(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP, string C_ADDRESS, string C_ZIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_KEYED_AUTHONLY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_KEYED_AUTHONLY(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_KEYED_FORCE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_KEYED_FORCE(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP, string T_AUTH);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RETAIL_KEYED_CREDIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RETAIL_KEYED_CREDIT(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RECURRING_SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RECURRING_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/BANKCARD_RECURRING_AUTHONLY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BANKCARD_RECURRING_AUTHONLY(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VERIFY_BANKCARD_SERVICE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VERIFY_BANKCARD_SERVICE(string M_ID, string M_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VERIFY_EFT_SERVICE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VERIFY_EFT_SERVICE(string M_ID, string M_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/vterm_extensions/TRANSACTION_PROCESSING" +
            "/VIRTUAL_CHECK_PPD_SALE_WITH_AUTHENTICATION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VIRTUAL_CHECK_PPD_SALE_WITH_AUTHENTICATION(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_SSN, 
                    string C_DL_STATE_CODE, 
                    string C_DL_NUMBER, 
                    string C_DOB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TRANSACTION_PROCESSINGSoapChannel : CmsData.SagePaymentsAPI.TRANSACTION_PROCESSINGSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TRANSACTION_PROCESSINGSoapClient : System.ServiceModel.ClientBase<CmsData.SagePaymentsAPI.TRANSACTION_PROCESSINGSoap>, CmsData.SagePaymentsAPI.TRANSACTION_PROCESSINGSoap {
        
        public TRANSACTION_PROCESSINGSoapClient() {
        }
        
        public TRANSACTION_PROCESSINGSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TRANSACTION_PROCESSINGSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TRANSACTION_PROCESSINGSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TRANSACTION_PROCESSINGSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet BANKCARD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.BANKCARD_SALE(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_CARDNUMBER, C_EXP, C_CVV, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet BANKCARD_CREDIT_OR_REFUND(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.BANKCARD_CREDIT_OR_REFUND(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_CARDNUMBER, C_EXP, C_CVV, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet BANKCARD_AUTHONLY(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.BANKCARD_AUTHONLY(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_CARDNUMBER, C_EXP, C_CVV, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet BANKCARD_CREDIT(string M_ID, string M_KEY, string T_AMT, string T_REFERENCE) {
            return base.Channel.BANKCARD_CREDIT(M_ID, M_KEY, T_AMT, T_REFERENCE);
        }
        
        public System.Data.DataSet BANKCARD_FORCE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_AUTH, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.BANKCARD_FORCE(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_CARDNUMBER, C_EXP, C_CVV, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_AUTH, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet BANKCARD_VOID(string M_ID, string M_KEY, string T_REFERENCE) {
            return base.Channel.BANKCARD_VOID(M_ID, M_KEY, T_REFERENCE);
        }
        
        public System.Data.DataSet BANKCARD_PRIOR_AUTH_SALE(string M_ID, string M_KEY, string T_AMT, string T_SHIPPING, string T_TAX, string T_AUTH, string T_REFERENCE) {
            return base.Channel.BANKCARD_PRIOR_AUTH_SALE(M_ID, M_KEY, T_AMT, T_SHIPPING, T_TAX, T_AUTH, T_REFERENCE);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_PPD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VIRTUAL_CHECK_PPD_SALE(M_ID, M_KEY, C_ORIGINATOR_ID, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_PPD_CREDIT(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VIRTUAL_CHECK_PPD_CREDIT(M_ID, M_KEY, C_ORIGINATOR_ID, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_CCD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_EIN, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VIRTUAL_CHECK_CCD_SALE(M_ID, M_KEY, C_ORIGINATOR_ID, C_EIN, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_CREDIT_BY_REFERENCE(string M_ID, string M_KEY, string T_AMT, string T_REFERENCE) {
            return base.Channel.VIRTUAL_CHECK_CREDIT_BY_REFERENCE(M_ID, M_KEY, T_AMT, T_REFERENCE);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_CCD_CREDIT(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_EIN, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VIRTUAL_CHECK_CCD_CREDIT(M_ID, M_KEY, C_ORIGINATOR_ID, C_EIN, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_WEB_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_SSN, 
                    string C_DL_STATE_CODE, 
                    string C_DL_NUMBER, 
                    string C_DOB) {
            return base.Channel.VIRTUAL_CHECK_WEB_SALE(M_ID, M_KEY, C_ORIGINATOR_ID, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY, C_SSN, C_DL_STATE_CODE, C_DL_NUMBER, C_DOB);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_VOID(string M_ID, string M_KEY, string T_REFERENCE) {
            return base.Channel.VIRTUAL_CHECK_VOID(M_ID, M_KEY, T_REFERENCE);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_RCK_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VIRTUAL_CHECK_RCK_SALE(M_ID, M_KEY, C_ORIGINATOR_ID, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_ARC_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string C_CHECK_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VIRTUAL_CHECK_ARC_SALE(M_ID, M_KEY, C_ORIGINATOR_ID, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, C_CHECK_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_TEL_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VIRTUAL_CHECK_TEL_SALE(M_ID, M_KEY, C_ORIGINATOR_ID, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_SWIPED_SALE(string M_ID, string M_KEY, string T_AMT, string T_TRACKDATA) {
            return base.Channel.BANKCARD_RETAIL_SWIPED_SALE(M_ID, M_KEY, T_AMT, T_TRACKDATA);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_SWIPED_AUTHONLY(string M_ID, string M_KEY, string T_AMT, string T_TRACKDATA) {
            return base.Channel.BANKCARD_RETAIL_SWIPED_AUTHONLY(M_ID, M_KEY, T_AMT, T_TRACKDATA);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_SWIPED_CREDIT(string M_ID, string M_KEY, string T_AMT, string T_TRACKDATA) {
            return base.Channel.BANKCARD_RETAIL_SWIPED_CREDIT(M_ID, M_KEY, T_AMT, T_TRACKDATA);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_KEYED_SALE(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP) {
            return base.Channel.BANKCARD_RETAIL_KEYED_SALE(M_ID, M_KEY, T_AMT, C_CARDNUMBER, C_EXP);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_KEYED_SALE_WITH_AVS(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP, string C_ADDRESS, string C_ZIP) {
            return base.Channel.BANKCARD_RETAIL_KEYED_SALE_WITH_AVS(M_ID, M_KEY, T_AMT, C_CARDNUMBER, C_EXP, C_ADDRESS, C_ZIP);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_KEYED_AUTHONLY_WITH_AVS(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP, string C_ADDRESS, string C_ZIP) {
            return base.Channel.BANKCARD_RETAIL_KEYED_AUTHONLY_WITH_AVS(M_ID, M_KEY, T_AMT, C_CARDNUMBER, C_EXP, C_ADDRESS, C_ZIP);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_KEYED_AUTHONLY(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP) {
            return base.Channel.BANKCARD_RETAIL_KEYED_AUTHONLY(M_ID, M_KEY, T_AMT, C_CARDNUMBER, C_EXP);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_KEYED_FORCE(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP, string T_AUTH) {
            return base.Channel.BANKCARD_RETAIL_KEYED_FORCE(M_ID, M_KEY, T_AMT, C_CARDNUMBER, C_EXP, T_AUTH);
        }
        
        public System.Data.DataSet BANKCARD_RETAIL_KEYED_CREDIT(string M_ID, string M_KEY, string T_AMT, string C_CARDNUMBER, string C_EXP) {
            return base.Channel.BANKCARD_RETAIL_KEYED_CREDIT(M_ID, M_KEY, T_AMT, C_CARDNUMBER, C_EXP);
        }
        
        public System.Data.DataSet BANKCARD_RECURRING_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.BANKCARD_RECURRING_SALE(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_CARDNUMBER, C_EXP, C_CVV, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet BANKCARD_RECURRING_AUTHONLY(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_CARDNUMBER, 
                    string C_EXP, 
                    string C_CVV, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.BANKCARD_RECURRING_AUTHONLY(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_CARDNUMBER, C_EXP, C_CVV, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VERIFY_BANKCARD_SERVICE(string M_ID, string M_KEY) {
            return base.Channel.VERIFY_BANKCARD_SERVICE(M_ID, M_KEY);
        }
        
        public System.Data.DataSet VERIFY_EFT_SERVICE(string M_ID, string M_KEY) {
            return base.Channel.VERIFY_EFT_SERVICE(M_ID, M_KEY);
        }
        
        public System.Data.DataSet VIRTUAL_CHECK_PPD_SALE_WITH_AUTHENTICATION(
                    string M_ID, 
                    string M_KEY, 
                    string C_ORIGINATOR_ID, 
                    string C_FIRST_NAME, 
                    string C_MIDDLE_INITIAL, 
                    string C_LAST_NAME, 
                    string C_SUFFIX, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string C_RTE, 
                    string C_ACCT, 
                    string C_ACCT_TYPE, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_SSN, 
                    string C_DL_STATE_CODE, 
                    string C_DL_NUMBER, 
                    string C_DOB) {
            return base.Channel.VIRTUAL_CHECK_PPD_SALE_WITH_AUTHENTICATION(M_ID, M_KEY, C_ORIGINATOR_ID, C_FIRST_NAME, C_MIDDLE_INITIAL, C_LAST_NAME, C_SUFFIX, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, C_RTE, C_ACCT, C_ACCT_TYPE, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY, C_SSN, C_DL_STATE_CODE, C_DL_NUMBER, C_DOB);
        }
    }
}
