#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsWeb.Areas.Main.Views.Coupon
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Main\Views\Coupon\List.cshtml"
    using UtilityExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Main/Views/Coupon/List.cshtml")]
    public class List : System.Web.Mvc.WebViewPage<CmsWeb.Models.CouponModel>
    {
        public List()
        {
        }
        public override void Execute()
        {


WriteLiteral(@"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">
<html xmlns=""http://www.w3.org/1999/xhtml"" >
<body style=""font-family:Arial"">
    <script src=""/Content/js/jquery-1.5.2.min.js"" type=""text/javascript""></script>
    <script type=""text/javascript"">
        $(function() {
            $(""a.confirm"").click(function() {
                return confirm(""are you sure?"");
            });
        });
    </script>
    <div>
    <form action=""/Coupon/List"" method=""post"">
    <table>
    <tr><td>User:</td><td>");


            
            #line 17 "..\..\Areas\Main\Views\Coupon\List.cshtml"
                     Write(Html.DropDownList("useridfilter", Model.Users()));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n    <tr><td>Reg:</td><td>");


            
            #line 18 "..\..\Areas\Main\Views\Coupon\List.cshtml"
                    Write(Html.DropDownList("regidfilter", Model.OnlineRegs()));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n    <tr><td>Status:</td><td>");


            
            #line 19 "..\..\Areas\Main\Views\Coupon\List.cshtml"
                       Write(Html.DropDownList("usedfilter", Model.CouponStatus()));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n    <tr><td>Name:</td><td>");


            
            #line 20 "..\..\Areas\Main\Views\Coupon\List.cshtml"
                     Write(Html.TextBox("name"));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n    <tr><td>Date:</td><td>");


            
            #line 21 "..\..\Areas\Main\Views\Coupon\List.cshtml"
                     Write(Html.TextBox("date"));

            
            #line default
            #line hidden
WriteLiteral(@"</td></tr>
    </table>
    <input name=""submit"" type=""submit"" value=""Search"" />
    <input name=""submit"" type=""submit"" value=""Excel"" />
    </form>
    </div>
    
    <table cellpadding=""4"" cellspacing=""0"">
        <tr>
            <th></th>
            <th>
            </th>
            <th>
                User<br />
                Purchaser<br />
                Person
            </th>
            <th>
                <br />
                Coupon Amt<br />
                Trans. Amt
            </th>
            <th>
                <br />
                <br />
                Registration
            </th>
            <th>
                Created<br />
                Used<br />
            </th>
        </tr>

");


            
            #line 54 "..\..\Areas\Main\Views\Coupon\List.cshtml"
   var n = 0; 

            
            #line default
            #line hidden

            
            #line 55 "..\..\Areas\Main\Views\Coupon\List.cshtml"
 foreach (var item in Model.Coupons()) 
{
    n++; 

            
            #line default
            #line hidden
WriteLiteral("        <tr ");


            
            #line 58 "..\..\Areas\Main\Views\Coupon\List.cshtml"
        Write((n % 2) == 0? "class='alt'" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n            <td>\r\n");


            
            #line 60 "..\..\Areas\Main\Views\Coupon\List.cshtml"
     if ((!item.Used.HasValue || item.Code.Length != 12) && !item.Canceled.HasValue)
    {
                
            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(Html.ActionLink("X", "Cancel", new { id = item.Code }, new { @class = "confirm" }));

            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\Main\Views\Coupon\List.cshtml"
                                                                                                   
    } 

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n            <td nowrap=\"nowrap\">\r\n                <span style=" +
"\"font-family:Courier New\">");


            
            #line 66 "..\..\Areas\Main\Views\Coupon\List.cshtml"
                                                 Write(item.Coupon);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 69 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(item.UserName);

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n                ");


            
            #line 70 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n                ");


            
            #line 71 "..\..\Areas\Main\Views\Coupon\List.cshtml"
            Write(item.Person ?? "na");

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td align=\"right\">\r\n                ");


            
            #line 74 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(item.Amount.ToString2("C"));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n                ");


            
            #line 75 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(item.RegAmt.ToString2("C"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 78 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(item.OrgDivName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 81 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(item.Created.FormatDateTm());

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n                ");


            
            #line 82 "..\..\Areas\Main\Views\Coupon\List.cshtml"
           Write(item.Used.FormatDateTm(item.Canceled.HasValue ? "canceled" : "not used"));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n            </td>\r\n            <td>\r\n            </td>\r\n        </tr>\r\n");


            
            #line 87 "..\..\Areas\Main\Views\Coupon\List.cshtml"
    
}

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n    <p>\r\n        ");


            
            #line 91 "..\..\Areas\Main\Views\Coupon\List.cshtml"
   Write(Html.ActionLink("Coupon", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n</body>\r\n</html>\r\n\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
