//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsData.SageVaultBankCardAPI {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard", ConfigurationName="SageVaultBankCardAPI.wsVaultBankcardSoap")]
    public interface wsVaultBankcardSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "SALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "AUTHONLY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_AUTHONLY(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "FORCE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_FORCE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_AUTH, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "CREDIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_CREDIT(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "SALE_CVV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_SALE_CVV(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "AUTHONLY_CVV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_AUTHONLY_CVV(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "SALE_RECURRING", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_SALE_RECURRING(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV, 
                    string T_RECURRING_PAYMENT);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sagepayments.net/web_services/wsVault/wsVaultBankcard/VAULT_BANKCARD_" +
            "AUTHONLY_RECURRING", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VAULT_BANKCARD_AUTHONLY_RECURRING(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV, 
                    string T_RECURRING_PAYMENT);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsVaultBankcardSoapChannel : CmsData.SageVaultBankCardAPI.wsVaultBankcardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsVaultBankcardSoapClient : System.ServiceModel.ClientBase<CmsData.SageVaultBankCardAPI.wsVaultBankcardSoap>, CmsData.SageVaultBankCardAPI.wsVaultBankcardSoap {
        
        public wsVaultBankcardSoapClient() {
        }
        
        public wsVaultBankcardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsVaultBankcardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVaultBankcardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVaultBankcardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet VAULT_BANKCARD_SALE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VAULT_BANKCARD_SALE(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VAULT_BANKCARD_AUTHONLY(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VAULT_BANKCARD_AUTHONLY(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VAULT_BANKCARD_FORCE(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_AUTH, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VAULT_BANKCARD_FORCE(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_AUTH, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VAULT_BANKCARD_CREDIT(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY) {
            return base.Channel.VAULT_BANKCARD_CREDIT(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY);
        }
        
        public System.Data.DataSet VAULT_BANKCARD_SALE_CVV(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV) {
            return base.Channel.VAULT_BANKCARD_SALE_CVV(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY, C_CVV);
        }
        
        public System.Data.DataSet VAULT_BANKCARD_AUTHONLY_CVV(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV) {
            return base.Channel.VAULT_BANKCARD_AUTHONLY_CVV(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY, C_CVV);
        }
        
        public System.Data.DataSet VAULT_BANKCARD_SALE_RECURRING(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV, 
                    string T_RECURRING_PAYMENT) {
            return base.Channel.VAULT_BANKCARD_SALE_RECURRING(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY, C_CVV, T_RECURRING_PAYMENT);
        }
        
        public System.Data.DataSet VAULT_BANKCARD_AUTHONLY_RECURRING(
                    string M_ID, 
                    string M_KEY, 
                    string C_NAME, 
                    string C_ADDRESS, 
                    string C_CITY, 
                    string C_STATE, 
                    string C_ZIP, 
                    string C_COUNTRY, 
                    string C_EMAIL, 
                    string GUID, 
                    string T_CUSTOMER_NUMBER, 
                    string T_AMT, 
                    string T_SHIPPING, 
                    string T_TAX, 
                    string T_ORDERNUM, 
                    string C_TELEPHONE, 
                    string C_FAX, 
                    string C_SHIP_NAME, 
                    string C_SHIP_ADDRESS, 
                    string C_SHIP_CITY, 
                    string C_SHIP_STATE, 
                    string C_SHIP_ZIP, 
                    string C_SHIP_COUNTRY, 
                    string C_CVV, 
                    string T_RECURRING_PAYMENT) {
            return base.Channel.VAULT_BANKCARD_AUTHONLY_RECURRING(M_ID, M_KEY, C_NAME, C_ADDRESS, C_CITY, C_STATE, C_ZIP, C_COUNTRY, C_EMAIL, GUID, T_CUSTOMER_NUMBER, T_AMT, T_SHIPPING, T_TAX, T_ORDERNUM, C_TELEPHONE, C_FAX, C_SHIP_NAME, C_SHIP_ADDRESS, C_SHIP_CITY, C_SHIP_STATE, C_SHIP_ZIP, C_SHIP_COUNTRY, C_CVV, T_RECURRING_PAYMENT);
        }
    }
}
