<%@ Page Language="C#" AutoEventWireup="true" StylesheetTheme="Standard" MasterPageFile="~/Site.Master" CodeBehind="UsersEmailFor.aspx.cs" Inherits="CMSWeb.Admin.UsersEmailFor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <asp:DynamicDataManager ID="DynamicDataManager1" runat="server"/>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="false" AutoGenerateDeleteButton="true"
            AutoGenerateColumns="false" DataSourceID="LinqDataSource1" AllowPaging="True" 
            AllowSorting="True" PageSize="200">
  <Columns>
    <asp:DynamicField DataField="UserId" />
    <asp:DynamicField DataField="CanEmailFor" />
  </Columns>    
        </asp:GridView>    
        <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
            ContextTypeName="CmsData.CMSDataContext" EnableUpdate="False" 
            TableName="UserCanEmailFors" EnableInsert="True" EnableDelete="True">
        </asp:LinqDataSource>
    <asp:Label ID="Label1" runat="server" Text="UserId"></asp:Label><asp:TextBox ID="UserId" runat="server"></asp:TextBox>
    <asp:Label ID="Label2" runat="server" Text="CanEmailFor"></asp:Label><asp:TextBox ID="CanEmailFor" runat="server"></asp:TextBox>
    <asp:Button ID="Insert" runat="server" Text="Button" onclick="Insert_Click" />
    </asp:Content>
