#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsWeb.Areas.Manage.Views.Emails
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
    using CmsWeb;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
    using UtilityExtensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manage/Views/Emails/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<CmsWeb.Models.EmailModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


            
            #line 5 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
  
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/SiteLayout.cshtml";


            
            #line default
            #line hidden

DefineSection("scripts", () => {

WriteLiteral(@"
<script type=""text/javascript"">
    $(function () {
        $(""#filter"").change(function () {
            window.location = window.location.pathname + ""?filter="" + $(this).val();
        });
        $(""table.grid > tbody > tr:even"").addClass(""alt"");
        $("".bt"").button();
    });

</script>
");


});

WriteLiteral("\r\n\r\n");


            
            #line 23 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 24 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
  
    var ts = new TimeSpan(0);
    if (Model.queue.Sent.HasValue && Model.queue.Started.HasValue) {
        ts = Model.queue.Sent.Value.Subtract(Model.queue.Started.Value);
    }
    var dt = new DateTime(ts.Ticks);


            
            #line default
            #line hidden
WriteLiteral("<table class=\"roundbox\">\r\n<tr><td colspan=\"2\"><h2>Details</h2></td></tr>\r\n<tr><td" +
">QueuedBy</td><td>");


            
            #line 33 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                    Write(Model.queue.QueuedBy);

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n<tr><td>FromName</td><td>");


            
            #line 34 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                    Write(Model.queue.FromName);

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n<tr><td>FromAddr</td><td>");


            
            #line 35 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                    Write(Model.queue.FromAddr);

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n<tr><td>Count</td><td>");


            
            #line 36 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                 Write(Model.GetEmailTos().Count());

            
            #line default
            #line hidden
WriteLiteral("</tr>\r\n<tr><td>Opens</td>\r\n    <td>");


            
            #line 38 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
   Write(Model.queue.EmailResponses.Count());

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 39 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
   Write(Html.DropDownList("filter", new SelectList( new string[] { "All", "Opened", "Not Opened" })));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td></tr>\r\n<tr><td>Unique Opens</td><td>");


            
            #line 41 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                        Write(Model.queue.EmailResponses.Select(er => er.PeopleId).Distinct().Count());

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n<tr><td>SendWhen</td><td>");


            
            #line 42 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                    Write(Model.queue.SendWhen.FormatDateTm());

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n<tr><td>Sent</td><td>");


            
            #line 43 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                Write(Model.queue.Sent.FormatDateTm());

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n<tr><td>Queued</td><td>");


            
            #line 44 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                  Write(Model.queue.Queued.FormatDateTm());

            
            #line default
            #line hidden
WriteLiteral(" \r\n");


            
            #line 45 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
 if (Model.CanDelete())
{

            
            #line default
            #line hidden
WriteLiteral("    <a href=\"/Manage/Emails/DeleteQueued/");


            
            #line 47 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                                    Write(Model.queue.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"bt\">Delete</a>\r\n");


            
            #line 48 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    </td></tr>\r\n<tr><td>Started</td><td>");


            
            #line 50 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                   Write(Model.queue.Started.FormatDateTm());

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n<tr><td>RunTime</td><td>");


            
            #line 51 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                   Write(dt.ToString("H:mm:ss"));

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n</table>\r\n");


            
            #line 53 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
 if (Model.queue.PublicX ?? false)
{

            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
Write(Html.ActionLink("View Email", "View", new { id = Model.id }));

            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                                                             
}
else if (Model.CanDelete())
{

            
            #line default
            #line hidden
WriteLiteral("    <a href=\"/Manage/Emails/MakePublic/");


            
            #line 59 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                                  Write(Model.queue.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"bt\">Make Public</a>\r\n");


            
            #line 60 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<h2>");


            
            #line 61 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
Write(Html.Raw(Model.queue.Subject));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<div style=\"max-width: 600px\">");


            
            #line 62 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                         Write(Html.Raw(Model.queue.Body));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<hr />\r\n<h2>Recipients</h2>\r\n<form action=\"/Manage/Emails/Recipients/");


            
            #line 65 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
                                   Write(Model.id);

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\">\r\n");


            
            #line 66 "..\..\Areas\Manage\Views\Emails\Details.cshtml"
  Html.RenderPartial("Recipients", Model);

            
            #line default
            #line hidden
WriteLiteral("</form>");


        }
    }
}
#pragma warning restore 1591
